config/routes.rb
require 'api'
Slyu::Application.routes.draw do
  get "admin/index"

  resources :sensors do
    get 'online(/:mac)'=>'sensors#online', :on => :collection
  end

  resources :bulletins

  resources :articles

  resources :categories

  get "rooms/index"
  get "rooms/light(/:id)" => "rooms#light", :as=> :room_light
  get "findroom/index"

  get "findroom/search"

  get "maps/index(/:id)" => 'maps#index', :as => :maps

  mount SLYU::API => "/" #API will be available under "/api" url because of setting from MyApp::API line 4
  devise_for :users

  get "home/index"
  get "home/about"

  namespace :admin do
    resources :buildings do
      resources :classrooms, :controller => 'building_classrooms'
      
      get 'import', :on => :collection
      post 'save_import', :on => :collection
    end
    resources :users do
      get 'generated_password', :on => :member
      get 'import', :on => :collection
      post 'save_import', :on => :collection
    end
  end

  root :to => 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :category_id, :content, :title
end

app/models/building.rb
class Building < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :name
  has_many :classrooms, :dependent => :destroy
  
  validates :name,  :presence => true,
                    :uniqueness => true
end

app/models/bulletin.rb
class Bulletin < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :building_id, :floor, :freeseats, :num, :seats
  belongs_to :building, :class_name => "Building", :foreign_key => "building_id"
  #has_one :sensor, :class_name => "Sensor", :foreign_key => "sensor_id"
  def roomno
    [floor, sprintf("%02d", num)].join()
  end
  validates :num,                 :length => { :minimum => 1 },
                                  :numericality => true,
                                  :presence => true
  validates :floor,               :numericality => { :only_integer => true, :greater_than_or_equal_to => 1 },
                                  :presence => true
  validates :seats,               :numericality => { :only_integer => true, :greater_than_or_equal_to => 10 },
                                  :presence => true
  validates_presence_of :building_id
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  attr_accessible :classroom_id, :ip, :mac, :online
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :excel_file
  # mount_uploader :excel_file, ExcelUploader
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, 
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :userid, :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "homepage", :except => [:about, :dashboard]
  def index
    #flash[:notice] = "Successfully created...Successfully created...Successfully created...Successfully created...Successfully created...Successfully "
  end
  
  def about
    
  end
  
  def dashboard
    
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @buildings = Building.all(:order=>"name")
    if params[:id].present?
      @building = Building.find(params[:id])
    end
  end
end

app/controllers/rooms_controller.rb
require 'open-uri'

class RoomsController < ApplicationController
  def index
    @buildings = Building.all(:order=>"name")
  end
  
  def light
    @room = Classroom.find(params[:id])
    @room.light =!@room.light
    
    if (@room.light)?(open("http://192.168.1.101/light/open")):(open("http://192.168.1.101/light/close"))
      respond_to do |format|
        if @room.update_attributes(params[:building])
          format.html { redirect_to rooms_index_path, notice: "Go" }
          format.json { head :no_content }
        else
          format.html { redirect_to rooms_index_path, notice: "Down" }
          format.json { render json: @building.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
          format.html { redirect_to rooms_index_path, notice: "Bad" }
          format.json { head :no_content }
      end
    end

  end
  
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sensors }
    end
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    @sensor = Sensor.find(params[:id])

    respond_to do |format|
      format.html # show.html.er77455b
      format.json { render json: @sensor }
    end
  end
  # GET /sensors/1
  # GET /sensors/1.json
  def online
    @sensor = Sensor.find_by_mac(params[:mac])
    @sensor.ip = request.remote_ip
    @sensor.online = true
    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render json: @sensor, status: :created, location: @sensor }
      else
        format.html { render action: "new" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # GET /sensors/new
  # GET /sensors/new.json
  def new
    @sensor = Sensor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sensor }
    end
  end

  # GET /sensors/1/edit
  def edit
    @sensor = Sensor.find(params[:id])
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(params[:sensor])

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render json: @sensor, status: :created, location: @sensor }
      else
        format.html { render action: "new" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sensors/1
  # PUT /sensors/1.json
  def update
    @sensor = Sensor.find(params[:id])

    respond_to do |format|
      if @sensor.update_attributes(params[:sensor])
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor = Sensor.find(params[:id])
    @sensor.destroy

    respond_to do |format|
      format.html { redirect_to sensors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/findroom_helper.rb
module FindroomHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/home/about.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/maps/index.html.erb
<% content_for :nav do -%>
<div>
<% if @buildings.present? %>
<ul class="nav nav-tabs nav-stacked">
    <li><%= link_to "临沂大学全貌", maps_url %></li>
    <% @buildings.each do |building| %>
       <li><%= link_to building.name, maps_url(building) %></li>
    <% end %>
</ul>
<% end %>
</div>
<% end -%>
<% if @building.present? %>
<h1 id=""><%= @building.name %></h1>
<%= gmaps({
          "map_options" => {"libraries" => ["places"], "center_longitude" => @building.longitude, "center_latitude" => @building.latitude, "zoom" => 20, "auto_adjust" => true, "type" => "SATELLITE"}
          }) 
%>
<% else %>
<h1 id="">临沂大学</h1>
<%= gmaps({
          "map_options" => {"libraries" => ["places"], "center_longitude" => 118.283985, "center_latitude" => 35.118456, "zoom" => 16, "auto_adjust" => true, "type" => "SATELLITE"}
          }) 
%>
<% end %>

app/views/rooms/index.html.erb
<ul id="BuildingTab" class="nav nav-tabs nav-stacked pull-left">
	<li class="active"><a href="#home" data-toggle="tab">教室总况</a></li>
    <% @buildings.each do |building| %>
	<li><%= link_to building.name, "#building_#{building.id}", "data-toggle"=>"tab" %></li>
    <% end %>
	<!-- <li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
	<ul class="dropdown-menu">
	<li class=""><a href="#dropdown1" data-toggle="tab">@fat</a></li>
	<li class=""><a href="#dropdown2" data-toggle="tab">@mdo</a></li>
	</ul>
	</li> -->
</ul>
<div id="BuildingTabContent" class="tab-content span7">
    <div class="tab-pane fade active in well well-small" id="home">
      <p>目前的耗电总况</p>
			
      <p>临沂大学共有教学建筑物<%= Building.all.size %>栋，</p>
      <p>共有教室<%= Classroom.all.size %>间，</p>
      <p>其中<%= Classroom.find_all_by_light(true).size %>间教室电源开启</p>
			
    </div>
	<% @buildings.each do |b| %>
    <div class="tab-pane fade" id="building_<%= b.id %>">
      <p>
	  
  	<div id="roomlist"class="well well-small">
  			<h3><%= b.name %></h3>
  			<% @classrooms_floor=b.classrooms.group_by{|s| s.floor} %>
  			<% @classrooms_floor.each do |floor,rooms| %>
  			<h4><%= floor %>楼</h4>
  			<div id="name" class="clearfix">
  			<ul>
  			    <% rooms.each do |room| %>
						<% if room.light==true %>
  				<li style="background:red">
						<% else %>
	  				<li style="background:blue">					
						<% end %>
						<%= link_to(room_light_path(room.id), :class => "roompopover", :rel => "popover", :title => "#{room.seats}", :"data-content" => "<b>hello popover world  #{room.freeseats}</b>",:"data-placement"=>"top", :"data-trigger"=>"hover") do %>
							<b><%= room.roomno%></b>
  					</a>
  				</li>
					<% end %>
  			    <% end %>
  			</ul>
  			</div>
  			<% end %>		
  		</div>
	  
	  
	  </p>
    </div>
	<% end %>
</div>