config/routes.rb
require 'api'
Slyu::Application.routes.draw do
  get "admin/index"

  resources :sensors do
    get 'online(/:mac)'=>'sensors#online', :on => :collection
  end

  resources :bulletins

  resources :articles

  resources :categories

  get "rooms/index"
  get "rooms/light(/:id)" => "rooms#light", :as=> :room_light
  get "findroom/index"

  get "findroom/search"

  get "maps/index(/:id)" => 'maps#index', :as => :maps

  mount SLYU::API => "/" #API will be available under "/api" url because of setting from MyApp::API line 4
  devise_for :users

  get "home/index"
  get "home/about"

  namespace :admin do
    resources :buildings do
      resources :classrooms, :controller => 'building_classrooms'
      
      get 'import', :on => :collection
      post 'save_import', :on => :collection
    end
    resources :users do
      get 'generated_password', :on => :member
      get 'import', :on => :collection
      post 'save_import', :on => :collection
    end
  end

  root :to => 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :category_id, :content, :title
end

app/models/building.rb
class Building < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :name
  has_many :classrooms, :dependent => :destroy
  
  validates :name,  :presence => true,
                    :uniqueness => true
end

app/models/bulletin.rb
class Bulletin < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :building_id, :floor, :freeseats, :num, :seats
  belongs_to :building, :class_name => "Building", :foreign_key => "building_id"
  #has_one :sensor, :class_name => "Sensor", :foreign_key => "sensor_id"
  def roomno
    [floor, sprintf("%02d", num)].join()
  end
  validates :num,                 :length => { :minimum => 1 },
                                  :numericality => true,
                                  :presence => true
  validates :floor,               :numericality => { :only_integer => true, :greater_than_or_equal_to => 1 },
                                  :presence => true
  validates :seats,               :numericality => { :only_integer => true, :greater_than_or_equal_to => 10 },
                                  :presence => true
  validates_presence_of :building_id
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  attr_accessible :classroom_id, :ip, :mac, :online
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :excel_file
  # mount_uploader :excel_file, ExcelUploader
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, 
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :userid, :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "homepage", :except => [:about, :dashboard]
  def index
    #flash[:notice] = "Successfully created...Successfully created...Successfully created...Successfully created...Successfully created...Successfully "
  end
  
  def about
    
  end
  
  def dashboard
    
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @buildings = Building.all(:order=>"name")
    if params[:id].present?
      @building = Building.find(params[:id])
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/findroom_helper.rb
module FindroomHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/admin/index.html.erb
<% content_for :nav do -%>
<div><%= render :partial => "shared/admin_bar" %></div>
<% end -%>
<h1>欢迎您<%= current_user.name %></h1>
<p>智慧临大是ThinkTeam参加第十届齐鲁软件设计大赛的作品</p>

app/views/shared/_admin_bar.html.erb
<div class="btn-group btn-group-vertical" style="width:100%">
	<button type="button" class="btn btn-large"><%= link_to "公告管理", bulletins_path %></button>
	<button type="button" class="btn btn-large"><%= link_to "建筑物管理", admin_buildings_path %></button>
	<button type="button" class="btn btn-large"><%= link_to "用户管理", admin_users_path %></button>
	<button type="button" class="btn btn-large"><%= link_to "新闻管理", articles_path %></button>
	</div>
	<br />
	<br />
	<div class="btn-group btn-group-vertical" style="width:100%">
		<button type="button" class="btn btn-large btn-success"><%= link_to "用户批量导入", import_admin_users_path %></button>
		<button type="button" class="btn btn-large btn-success"><%= link_to "建筑物信息批量导入", import_admin_buildings_path %></button>
		<button type="button" class="btn btn-large btn-success"><%= link_to "用户批量管理", admin_users_path %></button>
	</div>
	
	

app/views/shared/_browser.html.erb
<div class="modal hide" id="browser" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">您的浏览器版本太低了</h3>
  </div>
  <div class="modal-body">
    <p>您的浏览器版本太低了</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	<a href="https://www.google.com/intl/zh-CN/chrome/browser/" class="btn btn-primary">更换最快最强的浏览器</a>
  </div>
</div>

app/views/shared/_bulletins.html.erb
<% Bulletin.all(:limit=>5, :order => 'created_at DESC').each do |bulletin| %>
<li><i class="icon-bullhorn"></i>
	<%= link_to(bulletin.title, bulletin_path(bulletin), html_options = {:class => "", :rel => "popover", :title => "#{bulletin.title}", :"data-content" => "#{bulletin.content}",:"data-placement"=>"right", :"data-trigger"=>"hover"}) %>
</li><br />
<% end %>

app/views/shared/_footer.html.erb
<div class="container footer">
	<ul class="span12">
		<%= render :partial => "shared/footer_list" %>
		<li><%= link_to "", "" %><span class="copyright">© 2012 SmartLYU</span></li>
	</ul>
</div>
<ul class="span2 offset5">
	<%= render :partial => "shared/locale" %>
</ul>

app/views/shared/_footer_list.html.erb
<li><%= link_to "临沂大学", "http://www.lyu.edu.cn" %><span class="dot divider"> ·</span></li>
<li><%= link_to "关于", "" %><span class="dot divider"> ·</span></li>
<li><%= link_to "帮助", "" %><span class="dot divider"> ·</span></li>
<li><%= link_to "开发者", "" %><span class="dot divider"> ·</span></li>
<li><%= link_to "移动设备", "" %><span class="dot divider"> ·</span></li>
<li><%= link_to "服务器状态", "http://graphite.chunlea.org/" %><span class="dot divider"> ·</span></li>
<li><%= link_to "条款", "" %><span class="dot divider"> ·</span></li>
<li><%= link_to "隐私", "" %><span class="dot divider"> ·</span></li>
<li><%= link_to "资源", "" %><span class="dot divider"> ·</span></li>

app/views/shared/_homebox.html.erb
<div class="calendar">
	<div class="pull-left"><i class="icon-calendar"></i></div>
	<div class="date">
		<div id="name">
			&nbsp;<%= l Time.now, :format => :long %>
		</div>
		<div class="nongli">
			Welcome to Linyi University
		</div>
	</div>
</div>
<div class="barbox clearfix">
	<i class="icon-bullhorn"></i>
	<% if Bulletin.last.blank? %>
	<span class="badge badge-important"><%= Bulletin.all.size %></span>
	<% else %>
	  <%= link_to(bulletins_path, html_options = {:class => "", :rel => "popover", :title => "#{Bulletin.last.title}", :"data-content" => "#{Bulletin.last.content}",:"data-placement"=>"bottom", :"data-trigger"=>"hover"}) do%>
	<span class="badge badge-important"><%= Bulletin.all.size %></span>
	<% end %><% end %>
	&nbsp;
	
	<i class="icon-bullhorn"></i>
	<% if Article.last.blank? %>
	<span class="badge badge-important"><%= Article.all.size %></span>
	<% else %>
	  <%= link_to(bulletins_path, html_options = {:class => "", :rel => "popover", :title => "临大新闻：#{Article.last.title}", :"data-content" => "#{Article.last.content}",:"data-placement"=>"bottom", :"data-trigger"=>"hover"}) do%>
	<span class="badge badge-important"><%= Article.all.size %></span>
	<% end %><% end %>
	&nbsp;
	
	<i class="icon-home"></i>
	<% if Classroom.last.blank? %>
	<span class="badge badge-important"><%= Classroom.all.size %></span>
	<% else %>
	  <%= link_to(bulletins_path, html_options = {:class => "", :rel => "popover", :title => "共有教室#{Classroom.all.size}间", :"data-placement"=>"bottom", :"data-trigger"=>"hover"}) do%>
	<span class="badge badge-important"><%= Classroom.all.size %></span>
	<% end %><% end %>
	&nbsp;
	
	<i class="icon-user"></i>
	<% if User.last.blank? %>
	<span class="badge badge-important"><%= User.all.size %></span>
	<% else %>
	  <%= link_to(bulletins_path, html_options = {:class => "", :rel => "popover", :title => "共有教职工学生#{User.all.size}人", :"data-content" => "",:"data-placement"=>"bottom", :"data-trigger"=>"hover"}) do%>
	<span class="badge badge-important"><%= User.all.size %></span>
	<% end %><% end %>
	&nbsp;
		
	
</div>

app/views/shared/_locale.html.erb
<div class="btn-group dropup">
  <button class="btn primary">
	  <i class="icon-globe"></i>
	  Languages | 语言
  </button>
  <button class="btn primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
  <ul class="dropdown-menu pull-right">
    <li><%= link_to "简体中文", :controller => controller.controller_name, 
   	         :action => controller.action_name, :locale => "zh-CN" %>
	</li>
    <li><%= link_to "繁体中文", :controller => controller.controller_name, 
   	         :action => controller.action_name, :locale => "zh-TW" %>
	</li>
    <li><%= link_to "English", :controller => controller.controller_name, 
   	         :action => controller.action_name, :locale => "en" %>
	</li>
  </ul>
</div>

app/views/shared/_login.html.erb
<%= simple_form_for("user", :url => user_session_path, :class=>"form-horizontal") do |f| %>
<div class="pull-left">
	<div class="control-group">
		<div class="input-prepend">
			<span class="add-on"><i class="icon-user"></i></span>
			<%= f.text_field :userid, :class=>"span2", :id=>"prependedInput", :size=>"16", :placeholder=>"请输入工号或学号"%>
		</div>
	</div>
	<div class="control-group">  
		<div class="input-prepend">
			<span class="add-on"><i class="icon-key"></i></span>
			<%= f.password_field :password, :class=>"span2", :id=>"prependedInput", :size=>"16", :placeholder=>"请输入密码" %>
		</div>
	</div>
</div>
<div class="pull-right">
	<div class="control-group">
		<%= f.submit t("devise.sessions.login", :default => "Login"), :class=>"btn btn-primary"%>
		<%= link_to t("devise.sessions.findpass", :default => "Forget?"), new_password_path('user'), :class=>"btn btn-warning"%>
	</div>
	<div class="control-group form-inline">      
		<%= f.check_box :remember_me %>
		<%= f.label :remember, t("devise.sessions.remember") %>
	</label>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="#">智慧临大</a>
			<div class="container nav-collapse">
				<%= render_list :class => "nav" do |li|
							li << link_to("首页", root_path)
							li << link_to("临大动向", articles_path )
							li << link_to("物联教室", rooms_index_path)
							li << link_to("自习室查询", findroom_index_path )
							li << link_to("临大地图", maps_url)
							li << link_to("管理面板", admin_index_path )
						end %>
				<span class="navbar divider-vertical pull-right"></span>
				<form class="navbar-search pull-right">
					<input type="text" class="search-query" placeholder="临大综合搜索" x-webkit-speech  lang="zh-CN" >
				</form>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>

app/views/shared/_usercard.html.erb
<div class="usercard">
	<div class="userinfo pull-left">
		<div class="username">
			欢迎你，<span class="name"><%= current_user.name %></span>
		</div>
		<div class="userinfobox">
			&nbsp;
			<i class="icon-envelope"></i>
			<span class="badge badge-success">10</span>
			&nbsp;
			<i class="icon-tasks"></i>
			<span class="badge badge-important">10</span>	
			&nbsp;
		</div>
		<div class="usertools">
			&nbsp;
			<%= link_to(edit_admin_user_path(current_user)) do %> 
			<span class="label label-info">设置</span>
			<% end %>
			&nbsp;
			<%= link_to(destroy_user_session_path, :method => :delete) do %>        
			<span class="label label-important">退出</span>
			<% end %>
			&nbsp;
		</div>
	</div>
	<div class="avatar pull-right">
		<%= image_tag "avatar.gif", :title => "avatar", :class => "img-circle" %>
	</div>
</div>

app/views/shared/_usercardbar.html.erb
<div class="usercardbar pull-right">
	<div class="userinfo pull-left">
		<div class="username">
			欢迎你，<span class="name"><%= current_user.name %></span>
		</div>
		<div class="userinfobox">
			&nbsp;
			<i class="icon-envelope"></i>
			<span class="badge badge-success">10</span>
			&nbsp;
			<i class="icon-tasks"></i>
			<span class="badge badge-important">10</span>	
			&nbsp;
		</div>
		<div class="usertools">
			&nbsp;
			<%= link_to(edit_admin_user_path(current_user)) do %> 
			<span class="label label-info">设置</span>
			<% end %>
			&nbsp;
			<%= link_to(destroy_user_session_path, :method => :delete) do %>        
			<span class="label label-important">退出</span>
			<% end %>
			&nbsp;
		</div>
	</div>
	<div class="avatar pull-right">
		<%= image_tag "avatar.gif", :title => "avatar", :class => "img-circle" %>
	</div>
</div>

app/views/shared/bak_login.html.erb
<!--<h2>Sign in</h2>

<%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => { :class => 'form-horizontal' }) do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.email_field :email %>
    </div>
  </div>
  <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password %>
      </div>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class='control-group' >
      <%= f.label :remember_me, :class => 'control-label' %>
      <%= f.check_box :remember_me %> 
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit "Sign in", :class => 'btn' %>
  </div>
<% end %>

<%= render :partial => "devise/shared/links" %>
-->