config/routes.rb
require 'api'
Slyu::Application.routes.draw do
  get "admin/index"

  resources :sensors do
    get 'online(/:mac)'=>'sensors#online', :on => :collection
  end

  resources :bulletins

  resources :articles

  resources :categories

  get "rooms/index"
  get "rooms/light(/:id)" => "rooms#light", :as=> :room_light
  get "findroom/index"

  get "findroom/search"

  get "maps/index(/:id)" => 'maps#index', :as => :maps

  mount SLYU::API => "/" #API will be available under "/api" url because of setting from MyApp::API line 4
  devise_for :users

  get "home/index"
  get "home/about"

  namespace :admin do
    resources :buildings do
      resources :classrooms, :controller => 'building_classrooms'
      
      get 'import', :on => :collection
      post 'save_import', :on => :collection
    end
    resources :users do
      get 'generated_password', :on => :member
      get 'import', :on => :collection
      post 'save_import', :on => :collection
    end
  end

  root :to => 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :category_id, :content, :title
end

app/models/building.rb
class Building < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :name
  has_many :classrooms, :dependent => :destroy
  
  validates :name,  :presence => true,
                    :uniqueness => true
end

app/models/bulletin.rb
class Bulletin < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :building_id, :floor, :freeseats, :num, :seats
  belongs_to :building, :class_name => "Building", :foreign_key => "building_id"
  #has_one :sensor, :class_name => "Sensor", :foreign_key => "sensor_id"
  def roomno
    [floor, sprintf("%02d", num)].join()
  end
  validates :num,                 :length => { :minimum => 1 },
                                  :numericality => true,
                                  :presence => true
  validates :floor,               :numericality => { :only_integer => true, :greater_than_or_equal_to => 1 },
                                  :presence => true
  validates :seats,               :numericality => { :only_integer => true, :greater_than_or_equal_to => 10 },
                                  :presence => true
  validates_presence_of :building_id
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  attr_accessible :classroom_id, :ip, :mac, :online
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :excel_file
  # mount_uploader :excel_file, ExcelUploader
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, 
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :userid, :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
end

app/controllers/admin/building_classrooms_controller.rb
class Admin::BuildingClassroomsController < ApplicationController
  before_filter :find_building
  before_filter :authenticate_user!
  
  def index
    @classrooms = @building.classrooms(:order=>"floor,num")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classrooms }
    end    
  end

  def show
    @classroom = @building.classrooms.find( params[:id] )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classrooms }
    end
  end

  def new
    @classroom = @building.classrooms.build

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classrooms }
    end
  end

  def create
    @classroom = @building.classrooms.build( params[:classroom] )
    @classroom.freeseats = @classroom.seats
    @classroom.building.seats += @classroom.seats.to_i
    @classroom.building.freeseats += @classroom.seats.to_i
    @classroom.building.save
    respond_to do |format|
      if @classroom.save
        format.html { redirect_to admin_building_path( @building ), notice: t("notices.building_classroom.create") }
        format.json { render json: @building, status: :created, location: @building }
      else
        format.html { render action: "new" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @classroom = @building.classrooms.find( params[:id] )
  end

  def update
    @classroom = @building.classrooms.find( params[:id] )
    respond_to do |format|
      if @building.update_attributes(params[:building])
        format.html { redirect_to admin_building_path( @building ), notice: t("notices.building_classroom.update") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end    
  end

  def destroy
    @classroom = @building.classrooms.find( params[:id] )
    @classroom.destroy
  

    respond_to do |format|
      format.html { redirect_to admin_building_path( @building ) }
      format.json { head :no_content }
    end
  end

  protected

  def find_building
    @building = Building.find( params[:building_id] )
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "homepage", :except => [:about, :dashboard]
  def index
    #flash[:notice] = "Successfully created...Successfully created...Successfully created...Successfully created...Successfully created...Successfully "
  end
  
  def about
    
  end
  
  def dashboard
    
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @buildings = Building.all(:order=>"name")
    if params[:id].present?
      @building = Building.find(params[:id])
    end
  end
end

app/helpers/admin/building_classrooms_helper.rb
module Admin::BuildingClassroomsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/findroom_helper.rb
module FindroomHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/admin/building_classrooms/_form.html.erb
<%= simple_form_for [:admin, @building, @classroom], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :floor%>
  <%= f.input :num %>
  <%= f.input :seats %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_building_classrooms_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/building_classrooms/edit.html.erb
<div class="wellblock">
	<h1>编辑 <b><%= @building.name%></b> 的教室</h1>
</div>
<div class="wellblock">
<%= render 'form' %>
</div>

<%= link_to 'Show', @building_classroom %> |
<%= link_to 'Back', admin_building_classrooms_path %>

app/views/admin/building_classrooms/index.html.erb
<% content_for :nav do -%>
<div><%= render :partial => "shared/admin_bar" %></div>
<% end -%>
<%- model_class = Classroom -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:roomno) %></th>
      <th><%= model_class.human_attribute_name(:seats) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= link_to classroom.id, admin_building_classroom_path(@building, classroom) %></td>
        <td><%= classroom.roomno %></td>
        <td><%= classroom.seats %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_building_classroom_path(@building, classroom), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_building_classroom_path(@building, classroom),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_building_classroom_path(@building),
            :class => 'btn btn-primary' %>

app/views/admin/building_classrooms/new.html.erb
<%- model_class = Classroom -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/building_classrooms/show.html.erb
<%- model_class = Classroom -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:roomno) %>:</strong></dt>
  <dd><%= @classroom.roomno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:seats) %>:</strong></dt>
  <dd><%= @classroom.seats %></dd>
  <dt><strong><%= model_class.human_attribute_name(:building_id) %>:</strong></dt>
  <dd><%= @classroom.building_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_building_classrooms_path(@building, @classroom), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_building_classroom_path(@building, @classroom), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_building_classroom_path(@building, @classroom),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>